// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBookingProject.Server.Models;

#nullable disable

namespace TicketBookingProject.Server.Migrations
{
    [DbContext(typeof(TicketBookingProjectContext))]
    [Migration("20260331020713_AddAuditLogTable")]
    partial class AddAuditLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cancelled_reason");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("expires_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "IDX_b_created_at");

                    b.HasIndex(new[] { "EventId", "Status" }, "IDX_b_event_status");

                    b.HasIndex(new[] { "Status", "ExpiresAt" }, "IDX_b_status_expires");

                    b.HasIndex(new[] { "UserId" }, "IDX_b_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.BookingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int?>("EventSeatId")
                        .HasColumnType("int")
                        .HasColumnName("event_seat_id");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_type_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BookingId" }, "IDX_bd_booking_id");

                    b.HasIndex(new[] { "EventSeatId" }, "IDX_bd_event_seat_id");

                    b.HasIndex(new[] { "TicketTypeId" }, "IDX_bd_ticket_type_id");

                    b.ToTable("booking_details", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_categories_name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActiveAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("active_at");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("end_at");

                    b.Property<int>("MaxTicketsPerBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("max_tickets_per_booking");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime?>("SaleEndAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("sale_end_at");

                    b.Property<DateTime?>("SaleStartAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("sale_start_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex(new[] { "ActiveAt", "EndAt" }, "IDX_events_active_window");

                    b.HasIndex(new[] { "CategoryId" }, "IDX_events_category_id");

                    b.HasIndex(new[] { "OrganizerId" }, "IDX_events_organizer_id");

                    b.HasIndex(new[] { "SaleStartAt", "SaleEndAt" }, "IDX_events_sale_window");

                    b.HasIndex(new[] { "Status" }, "IDX_events_status");

                    b.HasIndex(new[] { "Status", "DeletedAt" }, "IDX_events_status_deleted");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventPoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<byte>("ImageType")
                        .HasColumnType("tinyint")
                        .HasColumnName("image_type");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "IDX_ep_event_id");

                    b.ToTable("event_posters", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<long?>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex(new[] { "EventId", "Status" }, "IDX_es_event_status");

                    b.HasIndex(new[] { "TicketTypeId" }, "IDX_es_ticket_type");

                    b.HasIndex(new[] { "EventId", "SeatId" }, "UQ_es_event_seat")
                        .IsUnique();

                    b.ToTable("event_seats", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventSeatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventSeatId")
                        .HasColumnType("int")
                        .HasColumnName("event_seat_id");

                    b.Property<byte?>("NewStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("new_status");

                    b.Property<byte?>("OldStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("old_status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BookingId" }, "IDX_esl_booking_id");

                    b.HasIndex(new[] { "CreatedAt" }, "IDX_esl_created_at");

                    b.HasIndex(new[] { "EventSeatId" }, "IDX_esl_event_seat_id");

                    b.ToTable("event_seat_logs", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MetaData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meta_data");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentTransaction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment_transaction");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BookingId", "Status" }, "IDX_pay_booking_status");

                    b.HasIndex(new[] { "PaymentMethod" }, "IDX_pay_method");

                    b.HasIndex(new[] { "Status" }, "IDX_pay_status");

                    b.HasIndex(new[] { "PaymentTransaction" }, "UQ_payments_transaction")
                        .IsUnique()
                        .HasFilter("[payment_transaction] IS NOT NULL");

                    b.HasIndex(new[] { "UserId", "IdempotencyKey" }, "UQ_payments_user_idempotency")
                        .IsUnique()
                        .HasFilter("[idempotency_key] IS NOT NULL");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("resource");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Action" }, "IDX_perm_action");

                    b.HasIndex(new[] { "Resource" }, "IDX_perm_resource");

                    b.HasIndex(new[] { "Name" }, "UQ_permissions_name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("RevokedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("revoked_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt" }, "IDX_rt_expires_at");

                    b.HasIndex(new[] { "Status" }, "IDX_rt_status");

                    b.HasIndex(new[] { "UserId" }, "IDX_rt_user_id");

                    b.HasIndex(new[] { "UserId", "Status" }, "IDX_rt_user_status");

                    b.HasIndex(new[] { "Token" }, "UQ_refresh_tokens_token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("processed_at");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("processed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex(new[] { "BookingId" }, "IDX_refunds_booking_id");

                    b.HasIndex(new[] { "PaymentId" }, "IDX_refunds_payment_id");

                    b.HasIndex(new[] { "Status" }, "IDX_refunds_status");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_roles_name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Row")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("row");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.Property<byte>("SeatType")
                        .HasColumnType("tinyint")
                        .HasColumnName("seat_type");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VenueId", "Row", "SeatNumber" }, "IDX_seat_position");

                    b.HasIndex(new[] { "SectionId" }, "IDX_seats_section_id");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.SeatHold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventSeatId")
                        .HasColumnType("int")
                        .HasColumnName("event_seat_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("expires_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "ExpiresAt" }, "IDX_sh_expires_at");

                    b.HasIndex(new[] { "Status", "ExpiresAt" }, "IDX_sh_status_exp");

                    b.HasIndex(new[] { "UserId", "Status" }, "IDX_sh_user_status");

                    b.HasIndex(new[] { "EventSeatId" }, "UQ_sh_event_seat_id")
                        .IsUnique();

                    b.ToTable("seat_holds", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("checked_in_at");

                    b.Property<int?>("CheckedInBy")
                        .HasColumnType("int")
                        .HasColumnName("checked_in_by");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventSeatId")
                        .HasColumnType("int")
                        .HasColumnName("event_seat_id");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("qr_code");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CheckedInBy");

                    b.HasIndex(new[] { "BookingId" }, "IDX_tickets_booking_id");

                    b.HasIndex(new[] { "EventSeatId" }, "IDX_tickets_event_seat_id");

                    b.HasIndex(new[] { "Status" }, "IDX_tickets_status");

                    b.HasIndex(new[] { "QrCode" }, "UQ_tickets_qr_code")
                        .IsUnique();

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("MaxPerUser")
                        .HasColumnType("int")
                        .HasColumnName("max_per_user");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int")
                        .HasColumnName("sold_quantity");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "IDX_tt_event_id");

                    b.HasIndex(new[] { "Status" }, "IDX_tt_status");

                    b.ToTable("ticket_types", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("lockout_end");

                    b.Property<byte>("LoginType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("login_type");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DeletedAt" }, "IDX_users_deleted_at");

                    b.HasIndex(new[] { "Status" }, "IDX_users_status");

                    b.HasIndex(new[] { "Email" }, "UQ_users_email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ_users_username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("address_detail");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("province");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.VenueSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VenueId" }, "IDX_vs_venue_id");

                    b.ToTable("venue_sections", (string)null);
                });

            modelBuilder.Entity("TicketBookingProject.Server.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<short>("Effect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasComment("1=allow, -1=deny (override role)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Effect");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rp_permission");

                    b.HasOne("TicketBookingProject.Server.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rp_role");
                });

            modelBuilder.Entity("TicketBookingProject.Server.AuditLog", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Booking", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_b_event");

                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_b_user");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.BookingDetail", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_bd_booking");

                    b.HasOne("TicketBookingProject.Server.Models.EventSeat", "EventSeat")
                        .WithMany("BookingDetails")
                        .HasForeignKey("EventSeatId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_bd_event_seat");

                    b.HasOne("TicketBookingProject.Server.Models.TicketType", "TicketType")
                        .WithMany("BookingDetails")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_bd_ticket_type");

                    b.Navigation("Booking");

                    b.Navigation("EventSeat");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Event", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_ev_category");

                    b.HasOne("TicketBookingProject.Server.Models.User", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK_ev_organizer");

                    b.HasOne("TicketBookingProject.Server.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_ev_venue");

                    b.Navigation("Category");

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventPoster", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Event", "Event")
                        .WithMany("EventPosters")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ep_event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventSeat", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Event", "Event")
                        .WithMany("EventSeats")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_es_event");

                    b.HasOne("TicketBookingProject.Server.Models.Seat", "Seat")
                        .WithMany("EventSeats")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK_es_seat");

                    b.HasOne("TicketBookingProject.Server.Models.TicketType", "TicketType")
                        .WithMany("EventSeats")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_es_ticket_type");

                    b.Navigation("Event");

                    b.Navigation("Seat");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventSeatLog", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Booking", "Booking")
                        .WithMany("EventSeatLogs")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_esl_booking");

                    b.HasOne("TicketBookingProject.Server.Models.EventSeat", "EventSeat")
                        .WithMany("EventSeatLogs")
                        .HasForeignKey("EventSeatId")
                        .IsRequired()
                        .HasConstraintName("FK_esl_event_seat");

                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany("EventSeatLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_esl_user");

                    b.Navigation("Booking");

                    b.Navigation("EventSeat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Payment", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_pay_booking");

                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_pay_user");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rt_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Refund", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Booking", "Booking")
                        .WithMany("Refunds")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_ref_booking");

                    b.HasOne("TicketBookingProject.Server.Models.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("FK_ref_payment");

                    b.HasOne("TicketBookingProject.Server.Models.User", "ProcessedByNavigation")
                        .WithMany("Refunds")
                        .HasForeignKey("ProcessedBy")
                        .HasConstraintName("FK_ref_processed_by");

                    b.Navigation("Booking");

                    b.Navigation("Payment");

                    b.Navigation("ProcessedByNavigation");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Seat", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.VenueSection", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_seat_section");

                    b.HasOne("TicketBookingProject.Server.Models.Venue", "Venue")
                        .WithMany("Seats")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_seat_venue");

                    b.Navigation("Section");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.SeatHold", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Booking", "Booking")
                        .WithMany("SeatHolds")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_sh_booking");

                    b.HasOne("TicketBookingProject.Server.Models.EventSeat", "EventSeat")
                        .WithOne("SeatHold")
                        .HasForeignKey("TicketBookingProject.Server.Models.SeatHold", "EventSeatId")
                        .IsRequired()
                        .HasConstraintName("FK_sh_event_seat");

                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany("SeatHolds")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_sh_user");

                    b.Navigation("Booking");

                    b.Navigation("EventSeat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Ticket", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_t_booking");

                    b.HasOne("TicketBookingProject.Server.Models.User", "CheckedInByNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("CheckedInBy")
                        .HasConstraintName("FK_t_checked_by");

                    b.HasOne("TicketBookingProject.Server.Models.EventSeat", "EventSeat")
                        .WithMany("Tickets")
                        .HasForeignKey("EventSeatId")
                        .IsRequired()
                        .HasConstraintName("FK_t_event_seat");

                    b.Navigation("Booking");

                    b.Navigation("CheckedInByNavigation");

                    b.Navigation("EventSeat");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.TicketType", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tt_event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.VenueSection", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Venue", "Venue")
                        .WithMany("VenueSections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_vs_venue");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketBookingProject.Server.UserPermission", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBookingProject.Server.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("TicketBookingProject.Server.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ur_role");

                    b.HasOne("TicketBookingProject.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ur_user");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("EventSeatLogs");

                    b.Navigation("Payments");

                    b.Navigation("Refunds");

                    b.Navigation("SeatHolds");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Event", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("EventPosters");

                    b.Navigation("EventSeats");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.EventSeat", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("EventSeatLogs");

                    b.Navigation("SeatHold");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Seat", b =>
                {
                    b.Navigation("EventSeats");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.TicketType", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("EventSeats");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("EventSeatLogs");

                    b.Navigation("Events");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Refunds");

                    b.Navigation("SeatHolds");

                    b.Navigation("Tickets");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Seats");

                    b.Navigation("VenueSections");
                });

            modelBuilder.Entity("TicketBookingProject.Server.Models.VenueSection", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
